# Generated by Django 3.1.5 on 2021-01-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('modelwithname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves_app.modelwithname')),
            ],
            bases=('shelves_app.modelwithname',),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('modelwithname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves_app.modelwithname')),
            ],
            bases=('shelves_app.modelwithname',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('modelwithname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves_app.modelwithname')),
                ('position', models.IntegerField()),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves_app.author')),
                ('book_shelf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shelves_app.shelf')),
            ],
            bases=('shelves_app.modelwithname',),
        ),
    ]
